@WebApi_HostAddress = http://localhost:5043

POST {{WebApi_HostAddress}}/api/chat
Content-Type: application/json

{
  "message": "متى موعد الاختبار؟",
  "userRole": "student",
  "conversationId": "abc123",
  "userName": "Ali"
}

###
